# Indian License Plate Patterns
# This file contains patterns for Indian license plates

patterns:
  # Old format: XX ## XX ####
  old_format: "^[A-Z]{2}[0-9]{2}[A-Z]{2}[0-9]{4}$"

  # New format (BH series): XX ## XX ####  
  new_format: "^[A-Z]{2}[0-9]{2}[A-Z]{2}[0-9]{4}$"

  # Commercial vehicles: XX ## X ####
  commercial: "^[A-Z]{2}[0-9]{2}[A-Z]{1}[0-9]{4}$"

# Common Indian state codes
state_codes:
  - DL  # Delhi
  - MH  # Maharashtra
  - KA  # Karnataka
  - TN  # Tamil Nadu
  - AP  # Andhra Pradesh
  - UP  # Uttar Pradesh
  - WB  # West Bengal
  - RJ  # Rajasthan
  - GJ  # Gujarat
  - HR  # Haryana
